version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker 
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093 
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER 
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  store-producer:
    build:
      context: ./StoreProducer
    ports:
      - "5000:5000"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER_URL: kafka:9092

  mongodb-save:
    build:
      context: ./MangoDB-Save
    depends_on:
      - kafka
      - mongo
    environment:
      KAFKA_BROKER_URL: kafka:9092
      MONGODB_URL: mongodb://mongo:27017/

  mongodb-alert:
    build:
      context: ./MangoDB-Alert
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER_URL: kafka:9092

  turnover-calc:
    build:
      context: ./TurnoverCalc
    depends_on:
      - mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017/

  publish-to-kafka:
    build:
      context: ./PublishToKafka
    ports:
      - "5001:5000"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER_URL: kafka:9092

networks:
  default:
    driver: bridge

volumes:
  mongo-data:
