apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-producer
  template:
    metadata:
      labels:
        app: store-producer
    spec:
      containers:
      - name: store-producer
        image: your-store-producer-image
        ports:
        - containerPort: 5000
        env:
        - name: KAFKA_BROKER_URL
          value: kafka:9092
      volumes:
      # Define any volumes if required
