apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-alert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-alert
  template:
    metadata:
      labels:
        app: mongodb-alert
    spec:
      containers:
      - name: mongodb-alert
        image: your-mongodb-alert-image
        env:
        - name: KAFKA_BROKER_URL
          value: kafka:9092
